// Generated WebView AI engine for Zharph.
export const ENGINE_HTML = String.raw`<!doctype html><html><body><script>
(function(){
'use strict';
var URL='https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1',SEG='Xenova/segformer-b0-finetuned-ade-512-512',DEP='onnx-community/depth-anything-v2-small',lib=null;
function post(o){try{window.ReactNativeWebView.postMessage(JSON.stringify(o));}catch(e){}}
function fail(s,e){post({type:'error',stage:s,message:String(e&&e.message||e)});}
function tick(){return new Promise(function(r){setTimeout(r,20);});}
function rt(v,m){return Math.max(m,Math.round(v/m)*m);}
function imgData(im,w,h){var c=document.createElement('canvas');c.width=w;c.height=h;var x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,w,h);return x.getImageData(0,0,w,h);}
function tensor(id,w,h){var n=w*h,d=id.data,o=new Float32Array(3*n),m=[.485,.456,.406],s=[.229,.224,.225];for(var i=0;i<n;i++){o[i]=(d[i*4]/255-m[0])/s[0];o[n+i]=(d[i*4+1]/255-m[1])/s[1];o[n*2+i]=(d[i*4+2]/255-m[2])/s[2];}return new lib.Tensor('float32',o,[1,3,h,w]);}
function resize(src,sw,sh,dw,dh){var o=new Float32Array(dw*dh),xr=sw/dw,yr=sh/dh;for(var y=0;y<dh;y++)for(var x=0;x<dw;x++){var sx=Math.min(sw-1,Math.max(0,Math.floor((x+.5)*xr))),sy=Math.min(sh-1,Math.max(0,Math.floor((y+.5)*yr)));o[y*dw+x]=src[sy*sw+sx];}return o;}
function png(mask,w,h){var c=document.createElement('canvas');c.width=w;c.height=h;var x=c.getContext('2d'),d=x.createImageData(w,h);for(var i=0;i<mask.length;i++){d.data[i*4]=255;d.data[i*4+1]=255;d.data[i*4+2]=255;d.data[i*4+3]=mask[i]?255:0;}x.putImageData(d,0,0);return c.toDataURL('image/png').split(',')[1];}
function clean(m,w,h){var o=new Uint8Array(w*h);for(var y=0;y<h;y++)for(var x=0;x<w;x++){var c=0,n=0;for(var dy=-1;dy<=1;dy++)for(var dx=-1;dx<=1;dx++){var xx=x+dx,yy=y+dy;if(xx>=0&&xx<w&&yy>=0&&yy<h){n++;if(m[yy*w+xx])c++;}}o[y*w+x]=c>=Math.ceil(n*.5)?1:0;}return o;}
function names(id,C){var defs={sky:'Sky',building:'Building',house:'Building',skyscraper:'Building',tower:'Building',tree:'Trees & plants',palm:'Trees & plants',plant:'Trees & plants',flower:'Trees & plants',grass:'Grass',field:'Grass',earth:'Ground',land:'Ground',road:'Road',sidewalk:'Road',mountain:'Mountains',hill:'Mountains',rock:'Mountains',water:'Water',sea:'Water',river:'Water',lake:'Water',person:'Person',car:'Vehicle',bus:'Vehicle',truck:'Vehicle',bicycle:'Vehicle',animal:'Animal',wall:'Wall & fence',fence:'Wall & fence',bridge:'Bridge'},out=[],map=new Array(C);for(var i=0;i<C;i++){var raw=String(id&&id[i]||'class '+i).toLowerCase().split(',')[0].trim(),n=defs[raw]||raw.replace(/^./,function(c){return c.toUpperCase();});if(out.indexOf(n)<0)out.push(n);map[i]=out.indexOf(n);}return{list:out,map:map};}
async function init(){try{lib=await import(URL);lib.env.allowLocalModels=false;lib.env.useBrowserCache=true;try{lib.env.backends.onnx.wasm.numThreads=1;}catch(e){}post({type:'ready'});}catch(e){fail('init','Could not load the AI runtime. Check the internet connection.');}}
window.__analyze=async function(job){try{var W=job.width,H=job.height,L=Math.max(W,H);post({type:'progress',stage:'prepare',pct:0});await tick();var im=await new Promise(function(ok,no){var a=new Image();a.onload=function(){ok(a)};a.onerror=function(){no(new Error('Could not decode the image'))};a.src='data:image/jpeg;base64,'+job.base64;});
post({type:'progress',stage:'seg-download',pct:0});var seg=await lib.AutoModelForSemanticSegmentation.from_pretrained(SEG,{device:'wasm',dtype:'fp32',progress_callback:function(e){if(e.status==='progress')post({type:'progress',stage:'seg-download',pct:Math.round(e.progress||0)})}});
post({type:'progress',stage:'segment',pct:0});var sw=rt(W*512/L,32),sh=rt(H*512/L,32),so=await seg({pixel_values:tensor(imgData(im,sw,sh),sw,sh)}),C=so.logits.dims[1],lh=so.logits.dims[2],lw=so.logits.dims[3],log=so.logits.data,id=seg.config.id2label,g=names(id,C);try{await seg.dispose()}catch(e){}
var depth=null;try{post({type:'progress',stage:'depth-download',pct:0});var dm=await lib.AutoModelForDepthEstimation.from_pretrained(DEP,{device:'wasm',dtype:'q8',progress_callback:function(e){if(e.status==='progress')post({type:'progress',stage:'depth-download',pct:Math.round(e.progress||0)})}}),dw=rt(W*336/L,14),dh=rt(H*336/L,14),do_=await dm({pixel_values:tensor(imgData(im,dw,dh),dw,dh)}),dd=do_.predicted_depth.dims,raw=do_.predicted_depth.data,rd=resize(raw,dd[dd.length-1],dd[dd.length-2],W,H),mn=Infinity,mx=-Infinity;for(var z=0;z<rd.length;z++){mn=Math.min(mn,rd[z]);mx=Math.max(mx,rd[z]);}depth=new Float32Array(rd.length);for(z=0;z<rd.length;z++)depth[z]=(rd[z]-mn)/(mx-mn||1);try{await dm.dispose()}catch(e){}post({type:'progress',stage:'depth',pct:100});}catch(e){post({type:'warn',message:'Depth model unavailable; using semantic layers only'});}
post({type:'progress',stage:'refine',pct:0});var groups=[],total=lh*lw;
for(var k=0;k<g.list.length;k++){var low=new Uint8Array(total),count=0;for(var q=0;q<total;q++){var best=-1,bv=-1;for(var c=0;c<C;c++){var gi=g.map[c];if(gi!==k)continue;var v=log[c*total+q];if(v>bv){bv=v;best=c;}}if(best>=0){low[q]=1;count++;}}if(count/total<.008)continue;var mask=new Uint8Array(W*H);for(var y=0;y<H;y++)for(var x=0;x<W;x++){var sx=Math.min(lw-1,Math.floor(x*lw/W)),sy=Math.min(lh-1,Math.floor(y*lh/H));mask[y*W+x]=low[sy*lw+sx]?1:0;}mask=clean(mask,W,H);var area=0;for(var p=0;p<mask.length;p++)area+=mask[p];if(area/(W*H)<.006)continue;var near=null;if(depth){var bins=new Uint32Array(32),tot=0;for(p=0;p<mask.length;p++)if(mask[p]){bins[Math.min(31,Math.floor(depth[p]*32))]++;tot++;}var ac=0;for(var b=0;b<32;b++){ac+=bins[b];if(ac>=tot/2){near=(b+.5)/32;break;}}}groups.push({id:'layer-'+(groups.length+1),label:g.list[k],group:g.list[k],area:area/(W*H),nearness:near,mask:png(mask,W,H)});}
groups.sort(function(a,b){if(a.group==='Sky')return 1;if(b.group==='Sky')return -1;if(a.nearness!=null&&b.nearness!=null)return b.nearness-a.nearness;return b.area-a.area;});post({type:'result',width:W,height:H,layers:groups.slice(0,10),depthUsed:!!depth,timings:{total:0}});}catch(e){fail('analyze',e);}};
init();
})();
</script></body></html>`;