import React,{useMemo,useState} from 'react';
import {Alert,Dimensions,Image,Platform,PlatformColor,Pressable,ScrollView,StatusBar,StyleSheet,Switch,Text,View} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import * as ImagePicker from 'expo-image-picker';
import {MaterialCommunityIcons as Icon} from '@expo/vector-icons';

const W=Dimensions.get('window').width,P=16,G=10,CARD=(W-P*2-G*2)/3;
const dynamic=Platform.OS==='android'&&Number(Platform.Version)>=31;
const dc=(name,fallback)=>dynamic?PlatformColor('@android:color/'+name):fallback;
// Android 12+ exposes the wallpaper-derived Material You tonal palettes as system colors.
// The roles below follow Android's Material You dark-theme mapping.
const C={
 bg:dc('system_neutral1_900','#111318'),
 surface:dc('system_neutral1_800','#1A1B20'),
 surface2:dc('system_neutral2_800','#22242B'),
 surface3:dc('system_neutral2_700','#2A2C34'),
 primary:dc('system_accent1_200','#D7E2FF'),
 onPrimary:dc('system_accent1_800','#20304E'),
 text:dc('system_neutral1_100','#F2F2FA'),
 muted:dc('system_neutral1_300','#9699A6'),
 outline:dc('system_neutral2_700','#464852'),
 soft:dc('system_accent1_900','#39435D')
};
const pics=[
['Aurora','Nature','https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=800&q=85'],
['Mountain','Nature','https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=85'],
['Forest','Nature','https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=85'],
['Ocean','Minimal','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=85'],
['Dunes','Minimal','https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?auto=format&fit=crop&w=800&q=85'],
['Clouds','Sky','https://images.unsplash.com/photo-1499346030926-9a72daac6c63?auto=format&fit=crop&w=800&q=85'],
['Night','Abstract','https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=85'],
['City','Abstract','https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=85'],
['Desert','Minimal','https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=85']
].map((x,i)=>({id:String(i),title:x[0],cat:x[1],uri:x[2]}));
const tabs=['For you','Nature','Abstract','Minimal','Sky'];

function Btn({name,onPress,active=false}){return <Pressable onPress={onPress} style={[s.iconBtn,active&&s.iconActive]}><Icon name={name} size={23} color={active?C.primary:C.text}/></Pressable>}
function Card({item,saved,onOpen,onSave}){return <Pressable onPress={onOpen} style={({pressed})=>[s.card,pressed&&s.pressed]}><Image source={{uri:item.uri}} style={s.cardImg}/><LinearGradient colors={['transparent','rgba(0,0,0,.78)']} style={s.fill}/><Pressable onPress={onSave} style={s.heart}><Icon name={saved?'heart':'heart-outline'} size={17} color={saved?'#FFD9E3':'#fff'}/></Pressable><View style={s.label}><Text numberOfLines={1} style={s.cardTitle}>{item.title}</Text><Text style={s.cardCat}>{item.cat}</Text></View></Pressable>}
function Add({onPress}){return <Pressable onPress={onPress} style={({pressed})=>[s.add,pressed&&s.pressed]}><View style={s.plus}><Icon name="plus" size={28} color={C.onPrimary}/></View><Text style={s.addTitle}>Your photo</Text><Text style={s.addSub}>Create depth</Text></Pressable>}

export default function App(){
 const [tab,setTab]=useState('For you'),[page,setPage]=useState('Home'),[image,setImage]=useState(null);
 const [mine,setMine]=useState([]),[saved,setSaved]=useState([]),[depth,setDepth]=useState(72),[parallax,setParallax]=useState(true),[vignette,setVignette]=useState(true);
 const list=useMemo(()=>tab==='For you'?pics:pics.filter(x=>x.cat===tab),[tab]);
 const open=x=>{setImage(x);setPage('Editor')};
 const toggle=x=>setSaved(a=>a.some(y=>y.id===x.id)?a.filter(y=>y.id!==x.id):[x,...a]);
 const pick=async()=>{const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){Alert.alert('Photos permission','Allow photo access to use your own wallpaper.');return}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[9,16],quality:.95});if(!r.canceled){const x={id:'u'+Date.now(),title:'My photo',cat:'Personal',uri:r.assets[0].uri};setMine(a=>[x,...a]);setImage(x);setPage('Editor')}};
 if(page==='Editor'&&image)return <Editor image={image} depth={depth} setDepth={setDepth} parallax={parallax} setParallax={setParallax} vignette={vignette} setVignette={setVignette} saved={saved.some(x=>x.id===image.id)} onSave={()=>toggle(image)} back={()=>{setImage(null);setPage('Home')}}/>;
 return <View style={s.root}><StatusBar barStyle="light-content" backgroundColor={C.bg}/><View style={s.header}><Text style={s.brand}>Zharph</Text><View style={s.headerBtns}><Btn name="magnify" onPress={()=>setTab('For you')}/><Btn name="dots-vertical" onPress={()=>Alert.alert('Zharph','Depth wallpapers • Material You')}/></View></View>
 {page==='Home'&&<Home tab={tab} setTab={setTab} list={list} mine={mine} saved={saved} pick={pick} open={open} toggle={toggle}/>}
 {page==='Depth'&&<Depth image={image||pics[0]} pick={pick} open={()=>open(image||pics[0])}/>}
 {page==='Saved'&&<Saved saved={saved} open={open} toggle={toggle} home={()=>setPage('Home')}/>}
 {page==='Settings'&&<Settings parallax={parallax} setParallax={setParallax}/>}
 <Nav page={page} setPage={setPage} close={()=>setImage(null)}/></View>
}

function Home({tab,setTab,list,mine,saved,pick,open,toggle}){return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.home}>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{tabs.map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabOn]}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</ScrollView>
 <View style={s.section}><Text style={s.sectionTitle}>{tab}</Text><Text style={s.count}>{list.length+mine.length}</Text></View>
 <View style={s.grid}><Add onPress={pick}/>{mine.map(x=><Card key={x.id} item={x} saved={saved.some(y=>y.id===x.id)} onOpen={()=>open(x)} onSave={()=>toggle(x)}/>)}
 {list.map(x=><Card key={x.id} item={x} saved={saved.some(y=>y.id===x.id)} onOpen={()=>open(x)} onSave={()=>toggle(x)}/>)}</View></ScrollView>}

function Depth({image,pick,open}){return <ScrollView contentContainerStyle={s.page}><Text style={s.pageTitle}>Depth</Text><Text style={s.sub}>Turn any photo into a layered wallpaper.</Text><Pressable onPress={open} style={s.bigPreview}><Image source={{uri:image.uri}} style={s.fill}/><LinearGradient colors={['transparent','rgba(0,0,0,.72)']} style={s.fill}/><View style={s.chip}><Icon name="layers-triple" size={17} color={C.primary}/><Text style={s.chipText}>Depth preview</Text></View><View style={s.previewText}><Text style={s.previewBig}>Make it feel deeper.</Text><Text style={s.previewSmall}>Tap to open the editor</Text></View></Pressable><View style={s.featureRow}><Feature icon="image-filter-hdr" title="Layer aware"/><Feature icon="gesture-swipe" title="Parallax"/></View><Pressable onPress={pick} style={s.primary}><Icon name="image-plus" size={21} color={C.onPrimary}/><Text style={s.primaryText}>Choose a photo</Text></Pressable></ScrollView>}
function Feature({icon,title}){return <View style={s.feature}><View style={s.featureIcon}><Icon name={icon} size={22} color={C.primary}/></View><Text style={s.featureTitle}>{title}</Text><Text style={s.featureSub}>Designed for a subtle depth look.</Text></View>}

function Saved({saved,open,toggle,home}){return <ScrollView contentContainerStyle={s.page}><Text style={s.pageTitle}>Saved</Text><Text style={s.sub}>Your favorite Zharph wallpapers.</Text>{!saved.length?<View style={s.empty}><View style={s.emptyIcon}><Icon name="heart-outline" size={30} color={C.primary}/></View><Text style={s.emptyTitle}>Nothing saved yet</Text><Text style={s.emptySub}>Tap the heart on a wallpaper to keep it here.</Text><Pressable onPress={home} style={s.secondary}><Text style={s.secondaryText}>Browse wallpapers</Text></Pressable></View>:<View style={s.grid}>{saved.map(x=><Card key={x.id} item={x} saved onOpen={()=>open(x)} onSave={()=>toggle(x)}/>)}</View>}</ScrollView>}

function Settings({parallax,setParallax}){return <ScrollView contentContainerStyle={s.page}><Text style={s.pageTitle}>Settings</Text><Text style={s.sub}>Tune the Zharph experience.</Text><View style={s.settings}><Setting icon="gesture-swipe" title="Parallax motion" text="Keep depth motion enabled." value={parallax} onChange={setParallax}/><Setting icon="palette-outline" title="Material You" text={dynamic?'Colors follow your Android system palette.':'Material You fallback palette on this device.'}/><Setting icon="information-outline" title="About Zharph" text="Depth wallpapers, rebuilt from zero."/></View></ScrollView>}
function Setting({icon,title,text,value,onChange}){return <View style={s.setting}><View style={s.settingIcon}><Icon name={icon} size={22} color={C.primary}/></View><View style={{flex:1}}><Text style={s.settingTitle}>{title}</Text><Text style={s.settingSub}>{text}</Text></View>{onChange?<Switch value={value} onValueChange={onChange} trackColor={{false:C.surface3,true:C.soft}} thumbColor={value?C.primary:C.muted}/>:<Icon name="chevron-right" size={21} color={C.muted}/>}</View>}

function Editor({image,depth,setDepth,parallax,setParallax,vignette,setVignette,saved,onSave,back}){return <View style={s.editor}><StatusBar barStyle="light-content" backgroundColor="#08090C"/><View style={s.editorTop}><Btn name="arrow-left" onPress={back}/><Text style={s.editorTitle}>Editor</Text><Btn name={saved?'heart':'heart-outline'} active={saved} onPress={onSave}/></View><View style={s.editorPreview}><Image source={{uri:image.uri}} style={s.fill}/><LinearGradient colors={['rgba(8,9,12,.02)','rgba(8,9,12,'+(Math.min(.72,depth/130))+')']} style={s.fill}/>{vignette&&<View style={s.vignette}/>}<View style={[s.editorChip,{transform:[{translateY:-depth*.08}]}]}><Icon name="layers-triple" size={18} color={C.primary}/><Text style={s.chipText}>{parallax?'Parallax depth':'Depth preview'}</Text></View><View style={s.clock}><Text style={s.clockBig}>09:41</Text><Text style={s.clockSmall}>Monday · Zharph</Text></View></View><ScrollView contentContainerStyle={s.controls}><View style={s.row}><Text style={s.controlTitle}>Depth</Text><Text style={s.value}>{depth}%</Text></View><View style={s.track}><View style={[s.trackFill,{width:depth+'%'}]}/></View><View style={s.depths}>{[25,50,72,90].map(x=><Pressable key={x} onPress={()=>setDepth(x)} style={[s.depthBtn,depth===x&&s.depthBtnOn]}><Text style={[s.depthText,depth===x&&s.depthTextOn]}>{x}</Text></Pressable>)}</View><View style={s.editorSetting}><View style={s.settingIcon}><Icon name="gesture-swipe" size={21} color={C.primary}/></View><View style={{flex:1}}><Text style={s.settingTitle}>Parallax motion</Text><Text style={s.settingSub}>Give the depth layer subtle movement.</Text></View><Switch value={parallax} onValueChange={setParallax} trackColor={{false:C.surface3,true:C.soft}} thumbColor={parallax?C.primary:C.muted}/></View><View style={s.editorSetting}><View style={s.settingIcon}><Icon name="gradient-horizontal" size={21} color={C.primary}/></View><View style={{flex:1}}><Text style={s.settingTitle}>Soft vignette</Text><Text style={s.settingSub}>Focus attention toward the center.</Text></View><Switch value={vignette} onValueChange={setVignette} trackColor={{false:C.surface3,true:C.soft}} thumbColor={vignette?C.primary:C.muted}/></View><Pressable onPress={onSave} style={s.primary}><Icon name={saved?'check':'bookmark-plus'} size={21} color={C.onPrimary}/><Text style={s.primaryText}>{saved?'Saved to collection':'Save wallpaper'}</Text></Pressable></ScrollView></View>}

function Nav({page,setPage,close}){const items=[['Home','home-variant-outline'],['Depth','layers-triple-outline'],['Saved','heart-outline'],['Settings','cog-outline']];return <View style={s.nav}>{items.map(([name,icon])=>{const on=page===name;return <Pressable key={name} onPress={()=>{close();setPage(name)}} style={s.navItem}><View style={[s.navIcon,on&&s.navIconOn]}><Icon name={on?icon.replace('-outline',''):icon} size={22} color={on?C.onPrimary:C.muted}/></View><Text style={[s.navText,on&&s.navTextOn]}>{name}</Text></Pressable>})}</View>}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:C.bg},header:{height:78,paddingHorizontal:P,paddingTop:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{color:C.primary,fontSize:30,fontWeight:'700',letterSpacing:-1.1},headerBtns:{flexDirection:'row'},iconBtn:{width:46,height:46,borderRadius:23,alignItems:'center',justifyContent:'center'},iconActive:{backgroundColor:C.soft},
 home:{paddingHorizontal:P,paddingBottom:108},tabs:{gap:8,paddingVertical:2,marginBottom:18},tab:{height:42,paddingHorizontal:17,borderRadius:21,borderWidth:1,borderColor:C.outline,backgroundColor:C.surface,alignItems:'center',justifyContent:'center'},tabOn:{backgroundColor:C.primary,borderColor:C.primary},tabText:{color:C.muted,fontSize:14,fontWeight:'600'},tabTextOn:{color:C.onPrimary},
 section:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:12},sectionTitle:{color:C.text,fontSize:20,fontWeight:'700'},count:{color:C.muted,backgroundColor:C.surface2,borderRadius:12,paddingHorizontal:8,paddingVertical:4,fontSize:11,fontWeight:'700'},
 grid:{flexDirection:'row',flexWrap:'wrap',gap:G},card:{width:CARD,height:CARD*1.42,borderRadius:22,overflow:'hidden',backgroundColor:C.surface},pressed:{opacity:.82,transform:[{scale:.975}]},cardImg:{...StyleSheet.absoluteFillObject,width:undefined,height:undefined},fill:{...StyleSheet.absoluteFillObject},heart:{position:'absolute',top:8,right:8,width:34,height:34,borderRadius:17,backgroundColor:'rgba(17,19,24,.62)',alignItems:'center',justifyContent:'center'},label:{position:'absolute',left:11,right:8,bottom:10},cardTitle:{color:'#fff',fontSize:13,fontWeight:'700'},cardCat:{color:'rgba(255,255,255,.72)',fontSize:10,marginTop:2},
 add:{width:CARD,height:CARD*1.42,borderRadius:22,borderWidth:1.2,borderColor:C.outline,borderStyle:'dashed',backgroundColor:C.surface,alignItems:'center',justifyContent:'center'},plus:{width:54,height:54,borderRadius:27,backgroundColor:C.primary,alignItems:'center',justifyContent:'center',marginBottom:10},addTitle:{color:C.primary,fontSize:13,fontWeight:'700'},addSub:{color:C.muted,fontSize:11,marginTop:3},
 page:{paddingHorizontal:P,paddingBottom:120},pageTitle:{color:C.text,fontSize:30,fontWeight:'700',letterSpacing:-.8,marginTop:4},sub:{color:C.muted,fontSize:14,lineHeight:20,marginTop:5,marginBottom:20},bigPreview:{height:W*1.04,borderRadius:30,overflow:'hidden',backgroundColor:C.surface},chip:{position:'absolute',top:14,left:14,height:34,paddingHorizontal:12,borderRadius:17,backgroundColor:'rgba(20,22,28,.72)',flexDirection:'row',alignItems:'center',gap:7},chipText:{color:C.primary,fontSize:11,fontWeight:'700'},previewText:{position:'absolute',left:18,right:18,bottom:20},previewBig:{color:'#fff',fontSize:27,fontWeight:'700',letterSpacing:-.7},previewSmall:{color:'rgba(255,255,255,.72)',fontSize:13,marginTop:4},featureRow:{flexDirection:'row',gap:10,marginTop:12},feature:{flex:1,padding:15,borderRadius:24,backgroundColor:C.surface,borderWidth:1,borderColor:C.outline},featureIcon:{width:42,height:42,borderRadius:15,backgroundColor:C.surface3,alignItems:'center',justifyContent:'center',marginBottom:11},featureTitle:{color:C.text,fontSize:14,fontWeight:'700'},featureSub:{color:C.muted,fontSize:11,lineHeight:16,marginTop:4},primary:{height:54,borderRadius:27,backgroundColor:C.primary,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:9,marginTop:16},primaryText:{color:C.onPrimary,fontSize:15,fontWeight:'800'},secondary:{height:48,paddingHorizontal:22,borderRadius:24,borderWidth:1,borderColor:C.outline,alignItems:'center',justifyContent:'center',marginTop:18},secondaryText:{color:C.primary,fontWeight:'700'},
 empty:{minHeight:380,borderRadius:28,borderWidth:1,borderColor:C.outline,backgroundColor:C.surface,alignItems:'center',justifyContent:'center',padding:30},emptyIcon:{width:70,height:70,borderRadius:25,backgroundColor:C.surface3,alignItems:'center',justifyContent:'center',marginBottom:15},emptyTitle:{color:C.text,fontSize:19,fontWeight:'700'},emptySub:{color:C.muted,fontSize:13,lineHeight:19,textAlign:'center',marginTop:6,maxWidth:260},
 settings:{backgroundColor:C.surface,borderRadius:28,overflow:'hidden',borderWidth:1,borderColor:C.outline},setting:{minHeight:82,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:C.outline},settingIcon:{width:42,height:42,borderRadius:15,backgroundColor:C.surface3,alignItems:'center',justifyContent:'center'},settingTitle:{color:C.text,fontSize:14,fontWeight:'700'},settingSub:{color:C.muted,fontSize:11,lineHeight:16,marginTop:3},
 nav:{position:'absolute',left:12,right:12,bottom:12,height:78,borderRadius:28,backgroundColor:'#1C1E24',borderWidth:1,borderColor:C.outline,flexDirection:'row',alignItems:'center',justifyContent:'space-around',paddingHorizontal:6},navItem:{flex:1,alignItems:'center',justifyContent:'center',gap:3},navIcon:{width:50,height:34,borderRadius:17,alignItems:'center',justifyContent:'center'},navIconOn:{backgroundColor:C.primary},navText:{color:C.muted,fontSize:10,fontWeight:'600'},navTextOn:{color:C.primary,fontWeight:'800'},
 editor:{flex:1,backgroundColor:'#08090C'},editorTop:{height:72,paddingHorizontal:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},editorTitle:{color:C.primary,fontSize:17,fontWeight:'700'},editorPreview:{height:W*1.22,marginHorizontal:14,borderRadius:30,overflow:'hidden',backgroundColor:C.surface},vignette:{...StyleSheet.absoluteFillObject,borderWidth:36,borderColor:'rgba(0,0,0,.22)',borderRadius:30},editorChip:{position:'absolute',top:18,left:18,height:36,paddingHorizontal:12,borderRadius:18,backgroundColor:'rgba(16,18,23,.68)',flexDirection:'row',alignItems:'center',gap:7},clock:{position:'absolute',left:20,right:20,bottom:22},clockBig:{color:'#fff',fontSize:54,fontWeight:'300',letterSpacing:-2},clockSmall:{color:'rgba(255,255,255,.78)',fontSize:12,marginTop:2},controls:{padding:18,paddingBottom:35},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},controlTitle:{color:C.text,fontSize:17,fontWeight:'800'},value:{color:C.muted,fontSize:13,fontWeight:'700'},track:{height:6,borderRadius:3,backgroundColor:C.surface3,marginTop:15,overflow:'hidden'},trackFill:{height:6,borderRadius:3,backgroundColor:C.primary},depths:{flexDirection:'row',gap:8,marginTop:15},depthBtn:{flex:1,height:38,borderRadius:19,backgroundColor:C.surface,borderWidth:1,borderColor:C.outline,alignItems:'center',justifyContent:'center'},depthBtnOn:{backgroundColor:C.primary,borderColor:C.primary},depthText:{color:C.muted,fontSize:12,fontWeight:'700'},depthTextOn:{color:C.onPrimary},editorSetting:{minHeight:74,marginTop:10,padding:12,borderRadius:23,backgroundColor:C.surface,borderWidth:1,borderColor:C.outline,flexDirection:'row',alignItems:'center',gap:11}
});